version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - ./.cache/pgdata:/var/lib/postgresql
